""""license_02"

Revision ID: b7db3a535cb6
Revises: bc40082f8efa
Create Date: 2016-07-14 10:58:43.814763

"""

# revision identifiers, used by Alembic.
revision = 'b7db3a535cb6'
down_revision = 'bc40082f8efa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('max_vcpu', sa.Integer(), nullable=True))
    op.add_column('licenses', sa.Column('max_vdisk', sa.Integer(), nullable=True))
    op.add_column('licenses', sa.Column('max_vmem', sa.Integer(), nullable=True))
    op.drop_column('licenses', 'max_vmem_per_desktop')
    op.drop_column('licenses', 'max_vdisk_per_desktop')
    op.drop_column('licenses', 'max_vcpu_per_desktop')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('max_vcpu_per_desktop', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('licenses', sa.Column('max_vdisk_per_desktop', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('licenses', sa.Column('max_vmem_per_desktop', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('licenses', 'max_vmem')
    op.drop_column('licenses', 'max_vdisk')
    op.drop_column('licenses', 'max_vcpu')
    ### end Alembic commands ###
