"""remove_paramgroup

Revision ID: 40b1f86470c4
Revises: 8233e4f9a145
Create Date: 2016-08-08 09:58:45.522071

"""

# revision identifiers, used by Alembic.
revision = '40b1f86470c4'
down_revision = '8233e4f9a145'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parameters_ibfk_1', 'parameters', type_='foreignkey')
    op.drop_table('param_groups')
    op.add_column('parameters', sa.Column('group', sa.String(length=64), nullable=True))
    op.drop_column('parameters', 'group_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('parameters_ibfk_1', 'parameters', 'param_groups', ['group_id'], ['id'])
    op.drop_column('parameters', 'group')
    op.create_table('param_groups',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
