"""image_visibility

Revision ID: ae80b39ba3fb
Revises: 40b1f86470c4
Create Date: 2016-08-08 20:59:46.942635

"""

# revision identifiers, used by Alembic.
revision = 'ae80b39ba3fb'
down_revision = '40b1f86470c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('visibility', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'visibility')
    ### end Alembic commands ###
