""""hostinfo_01"

Revision ID: 4a7737b9f329
Revises: 06eb766441c2
Create Date: 2016-08-05 10:54:24.461682

"""

# revision identifiers, used by Alembic.
revision = '4a7737b9f329'
down_revision = '06eb766441c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostinfo', sa.Column('external_network_state', sa.String(length=64), nullable=True))
    op.add_column('hostinfo', sa.Column('management_network_state', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostinfo', 'management_network_state')
    op.drop_column('hostinfo', 'external_network_state')
    ### end Alembic commands ###
