""""remove_desktoptaskextra"

Revision ID: 8233e4f9a145
Revises: 5efe298ff679
Create Date: 2016-07-23 14:22:06.005381

"""

# revision identifiers, used by Alembic.
revision = '8233e4f9a145'
down_revision = '5efe298ff679'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desktop_task_extra')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desktop_task_extra',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('desktop_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('image_ref', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('flavor_ref', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
