""""hostinfo"

Revision ID: 06eb766441c2
Revises: 8233e4f9a145
Create Date: 2016-08-04 19:25:27.735751

"""

# revision identifiers, used by Alembic.
revision = '06eb766441c2'
down_revision = 'ae80b39ba3fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('host_name', sa.String(length=64), nullable=True),
    sa.Column('host_ip', sa.String(length=64), nullable=True),
    sa.Column('cpu_arch', sa.String(length=64), nullable=True),
    sa.Column('cpu_cores', sa.String(length=64), nullable=True),
    sa.Column('mem', sa.String(length=64), nullable=True),
    sa.Column('disk', sa.String(length=64), nullable=True),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('service_state', sa.String(length=64), nullable=True),
    sa.Column('host_status', sa.String(length=64), nullable=True),
    sa.Column('service_status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hostinfo')
    ### end Alembic commands ###
