"""log

Revision ID: a96d51e1001f
Revises: ace407b8c0af
Create Date: 2016-07-05 13:13:05.423366

"""

# revision identifiers, used by Alembic.
revision = 'a96d51e1001f'
down_revision = 'ace407b8c0af'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('log_useraction_ibfk_1', 'log_useraction', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('log_useraction_ibfk_1', 'log_useraction', 'users', ['userid'], ['username'])
    ### end Alembic commands ###