""""license_01"

Revision ID: bc40082f8efa
Revises: 0d1cf3dec27f
Create Date: 2016-07-13 15:40:30.892241

"""

# revision identifiers, used by Alembic.
revision = 'bc40082f8efa'
down_revision = '0d1cf3dec27f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('max_vdisk_per_desktop', sa.Integer(), nullable=True))
    op.add_column('licenses', sa.Column('max_vmem_per_desktop', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'max_vmem_per_desktop')
    op.drop_column('licenses', 'max_vdisk_per_desktop')
    ### end Alembic commands ###
