"""system_policy

Revision ID: 743dee150a90
Revises: 3d3b965e7856
Create Date: 2016-09-29 18:43:52.716351

"""

# revision identifiers, used by Alembic.
revision = '743dee150a90'
down_revision = '3d3b965e7856'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('enable_usb', sa.Boolean(), nullable=True),
    sa.Column('enable_clipboard', sa.Boolean(), nullable=True),
    sa.Column('enable_audio', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=True)
    op.add_column('courses', sa.Column('policy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'policies', ['policy_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'policy_id')
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_table('policies')
    ### end Alembic commands ###
