""""terminal_02"

Revision ID: ae10d3bbd3ad
Revises: 82f6d05e42a2
Create Date: 2016-06-24 15:09:49.972906

"""

# revision identifiers, used by Alembic.
revision = 'ae10d3bbd3ad'
down_revision = '82f6d05e42a2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terminals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('terminals_ibfk_2', 'terminals', type_='foreignkey')
    op.create_foreign_key(None, 'terminals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('terminals', 'terminal_user_id')
    op.drop_column('terminals', 'info')
    op.add_column('users', sa.Column('is_device', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_device')
    op.add_column('terminals', sa.Column('info', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('terminals', sa.Column('terminal_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'terminals', type_='foreignkey')
    op.create_foreign_key('terminals_ibfk_2', 'terminals', 'terminal_users', ['terminal_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('terminals', 'user_id')
    ### end Alembic commands ###
