""""license"

Revision ID: 82f6d05e42a2
Revises: 0105d597522c
Create Date: 2016-06-14 10:35:11.271322

"""

# revision identifiers, used by Alembic.
revision = '82f6d05e42a2'
down_revision = '0105d597522c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('system_serial_number', sa.String(length=64), nullable=True),
    sa.Column('server_url', sa.String(length=64), nullable=True),
    sa.Column('expired_time', sa.DateTime(), nullable=True),
    sa.Column('mac_address', sa.String(length=64), nullable=True),
    sa.Column('server_serial_number', sa.String(length=64), nullable=True),
    sa.Column('max_desktops', sa.Integer(), nullable=True),
    sa.Column('max_images', sa.Integer(), nullable=True),
    sa.Column('max_user', sa.Integer(), nullable=True),
    sa.Column('max_vcpu_per_desktop', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licenses')
    ### end Alembic commands ###
