""""hostinfo_02"

Revision ID: 2d274cd8b63b
Revises: 4a7737b9f329
Create Date: 2016-08-10 11:44:48.689839

"""

# revision identifiers, used by Alembic.
revision = '2d274cd8b63b'
down_revision = '4a7737b9f329'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostinfo', sa.Column('disk_used', sa.String(length=64), nullable=True))
    op.add_column('hostinfo', sa.Column('mem_used', sa.String(length=64), nullable=True))
    op.add_column('hostinfo', sa.Column('running_vms', sa.Integer(), nullable=True))
    op.add_column('hostinfo', sa.Column('vms', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostinfo', 'vms')
    op.drop_column('hostinfo', 'running_vms')
    op.drop_column('hostinfo', 'mem_used')
    op.drop_column('hostinfo', 'disk_used')
    ### end Alembic commands ###
